CREATE TABLE mails
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_from_id BIGINT,
    user_to_id   BIGINT,
    from_name    VARCHAR(255),
    to_name      VARCHAR(255),
    from_important BOOLEAN,
    to_important   BOOLEAN,
    subject      VARCHAR(255),
    message      VARCHAR(1024),
    date         TIMESTAMP with time zone,
    CONSTRAINT pk_mails PRIMARY KEY (id)
);

ALTER TABLE mails
    ADD CONSTRAINT FK_MAILS_ON_USERFROM FOREIGN KEY (user_from_id) REFERENCES users (id);

ALTER TABLE mails
    ADD CONSTRAINT FK_MAILS_ON_USERTO FOREIGN KEY (user_to_id) REFERENCES users (id);